(function(){
  'use strict';
  const root=document.getElementById('affiliateCurrentApp');
  if(!root)return;
  const PAGE=20;
  const state={tab:'dashboard',dashboard:null,settings:null,products:[],commissions:[],withdrawals:[],productOffset:0,commissionOffset:0,withdrawalOffset:0,productsMore:true,commissionsMore:true,withdrawalsMore:true,loading:false};
  const en=()=>((localStorage.getItem('lang')||document.documentElement.lang)==='en');
  const t=(ar,enText)=>en()?enText:ar;
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const money=value=>`${Number(value||0).toFixed(2)} AED`;
  const token=()=>{try{return localStorage.getItem('x2_token')||''}catch(_){return''}};
  const rpc=(name,params={})=>window.sbFetch(`rpc/${name}`,{method:'POST',body:JSON.stringify(params)});
  function toast(message){const node=document.createElement('div');node.className='affiliate-toast';node.textContent=message;document.body.appendChild(node);setTimeout(()=>node.remove(),2400)}
  function clearLegacy(){['x2-aff-id','x2-aff-total','x2-aff-pending','x2-aff-sales','x2-aff-transactions','x2-aff-logged-in','x2-aff-email','x2-aff-pass','x2-aff-name','x2-aff-activated','x2-aff-old-passwords'].forEach(key=>localStorage.removeItem(key))}
  function firstRow(raw){return Array.isArray(raw)?raw[0]:raw}

  async function boot(){
    clearLegacy();
    if(!window.sbFetch){renderError(t('تعذر الاتصال بخدمة الحساب.','Unable to connect to the account service.'));return}
    try{
      state.settings=firstRow(await window.sbFetch('affiliate_settings?id=eq.true&limit=1'))||{};
      if(!token()){renderGuest();return}
      state.dashboard=firstRow(await rpc('affiliate_dashboard'))||{};
      render();
    }catch(error){
      if(/401|jwt|auth/i.test(String(error))){renderGuest();return}
      renderError(String(error.message||error));
    }
  }

  function renderGuest(){root.innerHTML=`<div class="affiliate-panel affiliate-message"><h2>${t('برنامج شركاء بريق','Bariq Partner Program')}</h2><p>${t('سجل الدخول بحساب العميل نفسه لعرض حساب الشريك أو تقديم طلب انضمام.','Sign in with the same customer account to view your partner account or apply.')}</p><br><a class="affiliate-btn primary" href="/account">${t('تسجيل الدخول','Sign in')}</a></div>`}
  function renderError(message){root.innerHTML=`<div class="affiliate-panel affiliate-message"><h2>${t('تعذر تحميل برنامج الشركاء','Unable to load the partner program')}</h2><p>${esc(message)}</p><br><button class="affiliate-btn primary" id="affiliateRetry">${t('إعادة المحاولة','Retry')}</button></div>`;document.getElementById('affiliateRetry').onclick=boot}
  function render(){
    const partner=state.dashboard&&state.dashboard.partner;
    if(!partner){renderApplication();return}
    if(partner.status!=='active'){renderStatus(partner);return}
    root.innerHTML=`<div class="affiliate-shell">${hero(partner)}${tabs()}<div class="affiliate-content" id="affiliateContent"></div></div>`;
    root.querySelectorAll('.affiliate-tab').forEach(button=>button.onclick=()=>selectTab(button.dataset.tab));
    renderTab();
  }
  function hero(p){return `<div class="affiliate-hero"><div class="affiliate-avatar">${esc((p.full_name||'B').slice(0,1).toUpperCase())}</div><div><h1>${t('مرحبًا','Welcome')}, ${esc(p.account_name||p.full_name)}</h1><p>ID: ${esc(p.partner_code)} • ${esc(p.level||'partner')}</p></div><span class="affiliate-status">${t('نشط','Active')}</span></div>`}
  function tabs(){const rows=[['dashboard','▦',t('الرئيسية','Dashboard')],['market','◖',t('سوّق','Market')],['sales','▤',t('مبيعاتي','Sales')],['earnings','▣',t('أرباحي','Earnings')],['profile','●',t('ملفي','Profile')]];return `<div class="affiliate-tabs">${rows.map(row=>`<button class="affiliate-tab ${state.tab===row[0]?'active':''}" data-tab="${row[0]}"><span>${row[1]}</span><br>${row[2]}</button>`).join('')}</div>`}
  async function selectTab(tab){state.tab=tab;root.querySelectorAll('.affiliate-tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));renderTab();if(tab==='market'&&!state.products.length)await loadProducts();if(tab==='sales'&&!state.commissions.length)await loadCommissions();if(tab==='earnings'){if(!state.commissions.length)await loadCommissions();if(!state.withdrawals.length)await loadWithdrawals()}}
  function renderTab(){const content=document.getElementById('affiliateContent');if(!content)return;if(state.tab==='dashboard')content.innerHTML=overview();else if(state.tab==='market')content.innerHTML=market();else if(state.tab==='sales')content.innerHTML=sales();else if(state.tab==='earnings')content.innerHTML=earnings();else content.innerHTML=profile();bindTabActions()}
  function overview(){const d=state.dashboard;const rows=[[t('إجمالي المبيعات','Total sales'),d.total_sales,'AED'],[t('إجمالي الأرباح','Total earnings'),d.total_earnings,'AED'],[t('المتاح','Available'),d.available_earnings,'AED'],[t('المعلق','Pending'),d.pending_earnings,'AED'],[t('المدفوع','Paid'),d.paid_earnings,'AED'],[t('الطلبات','Orders'),d.order_count,''],[t('العملاء','Customers'),d.customer_count,''],[t('التحويل','Conversion'),d.conversion_rate,'%']];return `<h2>${t('لوحة الأداء المالي','Financial dashboard')}</h2><br><div class="affiliate-grid">${rows.map(x=>`<div class="affiliate-stat"><small>${x[0]}</small><strong>${Number(x[1]||0).toFixed(x[2]?2:0)} ${x[2]}</strong></div>`).join('')}</div>`}
  function market(){return `<h2>${t('سوّق واربح','Market & earn')}</h2><p>${t('شارك روابطك الخاصة وتابع العمولة المتوقعة لكل منتج.','Share your unique links and track expected profit for every product.')}</p><br><div id="affiliateProducts">${state.products.length?state.products.map(productCard).join(''):`<div class="affiliate-empty">${state.loading?t('جاري التحميل...','Loading...'):t('جاري تجهيز المنتجات...','Preparing products...')}</div>`}</div>${state.productsMore?`<button class="affiliate-btn affiliate-load-more" id="moreAffiliateProducts">${t('تحميل المزيد','Load more')}</button>`:''}`}
  function productCard(p){const name=en()?(p.name_en||p.name_ar):(p.name_ar||p.name_en);const image=p.image||(Array.isArray(p.gallery)?p.gallery[0]:'')||'';const rate=Number(p.affiliate_commission_rate||state.dashboard.partner.commission_override||state.settings.default_commission_rate||0);const link=`${location.origin}/product/${encodeURIComponent(p.id)}?ref=${encodeURIComponent(state.dashboard.partner.partner_code)}`;return `<article class="affiliate-card affiliate-product"><img src="${esc(image)}" alt=""><div><h3>${esc(name||t('منتج بريق','Bariq product'))}</h3><p>${money(p.price)} • ${rate.toFixed(0)}%</p><p>${t('ربحك المتوقع','Expected profit')}: ${money(Number(p.price||0)*rate/100)}</p><div class="affiliate-actions"><button class="affiliate-btn copy-product" data-link="${esc(link)}">${t('نسخ الرابط','Copy link')}</button><button class="affiliate-btn share-product" data-link="${esc(link)}" data-name="${esc(name)}">${t('مشاركة','Share')}</button><button class="affiliate-btn assets-product" data-id="${esc(p.id)}" data-link="${esc(link)}">${t('مواد التسويق','Marketing assets')}</button></div></div></article>`}
  function sales(){return `<h2>${t('مبيعاتي','My sales')}</h2><br>${state.commissions.length?state.commissions.map(c=>`<div class="affiliate-list-row"><div><strong>${t('طلب','Order')} #${esc(c.order_number)}</strong><small style="display:block;color:#7c879a">${new Date(c.created_at).toLocaleDateString(en()?'en-AE':'ar-AE')}</small></div><div><strong>${money(c.commission_amount)}</strong><small style="display:block">${esc(c.status)}</small></div></div>`).join(''):`<div class="affiliate-empty">${t('لا توجد مبيعات منسوبة إليك حتى الآن.','No attributed sales yet.')}</div>`}${state.commissionsMore?`<button class="affiliate-btn affiliate-load-more" id="moreAffiliateCommissions">${t('تحميل المزيد','Load more')}</button>`:''}`}
  function earnings(){return `<div class="affiliate-card" style="background:#152546;color:#fff"><small>${t('الرصيد المتاح','Available balance')}</small><h2 style="color:#e0b63f;margin:8px 0 14px">${money(state.dashboard.available_earnings)}</h2><button class="affiliate-btn gold" id="affiliateWithdraw" ${Number(state.dashboard.available_earnings||0)<Number(state.settings.minimum_withdrawal||0)?'disabled':''}>${t('طلب سحب','Request withdrawal')}</button></div><br><h3>${t('سجل السحب','Withdrawal history')}</h3><br>${state.withdrawals.length?state.withdrawals.map(w=>`<div class="affiliate-list-row"><span>${esc(w.payout_method)}</span><strong>${money(w.amount)} • ${esc(w.status)}</strong></div>`).join(''):`<div class="affiliate-empty">${t('لا توجد طلبات سحب.','No withdrawals yet.')}</div>`}${state.withdrawalsMore?`<button class="affiliate-btn affiliate-load-more" id="moreAffiliateWithdrawals">${t('تحميل المزيد','Load more')}</button>`:''}`}
  function profile(){const p=state.dashboard.partner;const link=`${location.origin}/?ref=${encodeURIComponent(p.partner_code)}`;return `<h2>${t('ملفي كشريك','My affiliate profile')}</h2><br><div class="affiliate-link">${esc(link)}</div><div class="affiliate-actions"><button class="affiliate-btn primary" id="copyPartnerLink">${t('نسخ رابط التسويق','Copy marketing link')}</button><button class="affiliate-btn" id="sharePartnerLink">${t('مشاركة','Share')}</button></div><br><form class="affiliate-form" id="affiliateProfileForm">${field('full_name',t('الاسم الكامل','Full name'),p.full_name,true)}${field('account_name',t('اسم حساب الشريك','Account name'),p.account_name,true)}${field('phone',t('رقم الهاتف','Phone'),p.phone,true)}${field('emirate',t('الإمارة','Emirate'),p.emirate)}${field('instagram','Instagram',p.instagram)}${field('tiktok','TikTok',p.tiktok)}${field('other_social',t('حساب تواصل آخر','Other social account'),p.other_social)}${field('marketing_method',t('طريقة التسويق','Marketing plan'),p.marketing_method,false,true)}${field('payout_method',t('طريقة استلام الأرباح','Payout method'),p.payout_method)}${field('payout_details',t('بيانات الحساب / IBAN','Account / IBAN details'),(p.payout_details||{}).details||'',false,true)}<button class="affiliate-btn primary wide" type="submit">${t('حفظ الملف','Save profile')}</button></form><br><button class="affiliate-btn danger" id="terminateAffiliate">${t('إنهاء التعاقد','End affiliate contract')}</button><div style="height:70px"></div>`}
  function field(name,label,value,required=false,area=false){return `<label class="${area?'wide':''}">${esc(label)}${required?' *':''}${area?`<textarea name="${name}" rows="3" ${required?'required':''}>${esc(value)}</textarea>`:`<input name="${name}" value="${esc(value)}" ${required?'required':''}>`}</label>`}
  function renderStatus(p){const labels={pending:t('قيد المراجعة','Under review'),suspended:t('موقوف','Suspended'),rejected:t('مرفوض','Rejected'),terminated:t('تم إنهاء التعاقد','Contract ended')};root.innerHTML=`<div class="affiliate-panel affiliate-message"><h2>${esc(labels[p.status]||p.status)}</h2><p>${p.status==='terminated'?t('توقفت روابط وأدوات التسويق مع الاحتفاظ بسجلاتك المالية السابقة.','Marketing links and tools are disabled while previous financial records remain preserved.'):t('ستتاح أدوات التسويق والسحب بعد موافقة الإدارة.','Marketing and withdrawal tools become available after admin approval.')}</p></div>`}
  function renderApplication(){root.innerHTML=`<div class="affiliate-panel" style="padding:18px"><h2>${t('الانضمام إلى برنامج شركاء بريق','Join Bariq Partner Program')}</h2><br><form class="affiliate-form" id="affiliateApplication">${field('full_name',t('الاسم الكامل','Full name'),'',true)}${field('account_name',t('اسم حساب الشريك','Partner account name'),'',true)}${field('phone',t('رقم الهاتف','Phone'),'',true)}${field('email',t('البريد الإلكتروني','Email'),currentEmail(),true)}${field('emirate',t('الإمارة','Emirate'),'',true)}${field('instagram','Instagram','')}${field('tiktok','TikTok','')}${field('other_social',t('حساب تواصل آخر','Other social account'),'')}${field('marketing_method',t('طريقة التسويق','Marketing method'),'',true,true)}<button class="affiliate-btn primary wide" type="submit">${t('إرسال طلب الانضمام','Submit application')}</button></form></div>`;document.getElementById('affiliateApplication').onsubmit=submitApplication}
  function currentEmail(){try{const part=token().split('.')[1].replace(/-/g,'+').replace(/_/g,'/');return JSON.parse(atob(part)).email||''}catch(_){return''}}
  async function submitApplication(event){event.preventDefault();const form=event.currentTarget;const payload=Object.fromEntries(new FormData(form));try{await rpc('affiliate_apply',{p_payload:payload});toast(t('تم إرسال الطلب','Application submitted'));await boot()}catch(error){toast(String(error.message||error))}}
  function bindTabActions(){
    const byId=id=>document.getElementById(id);
    root.querySelectorAll('.copy-product').forEach(x=>x.onclick=()=>copy(x.dataset.link));
    root.querySelectorAll('.share-product').forEach(x=>x.onclick=()=>share(`${x.dataset.name}\n${x.dataset.link}`));
    root.querySelectorAll('.assets-product').forEach(x=>x.onclick=()=>showAssets(x.dataset.id,x.dataset.link));
    if(byId('moreAffiliateProducts'))byId('moreAffiliateProducts').onclick=loadProducts;
    if(byId('moreAffiliateCommissions'))byId('moreAffiliateCommissions').onclick=loadCommissions;
    if(byId('moreAffiliateWithdrawals'))byId('moreAffiliateWithdrawals').onclick=loadWithdrawals;
    if(byId('copyPartnerLink'))byId('copyPartnerLink').onclick=()=>copy(`${location.origin}/?ref=${state.dashboard.partner.partner_code}`);
    if(byId('sharePartnerLink'))byId('sharePartnerLink').onclick=()=>share(`${t('تسوق هدايا بريق','Shop Bariq Gifts')}\n${location.origin}/?ref=${state.dashboard.partner.partner_code}`);
    if(byId('affiliateProfileForm'))byId('affiliateProfileForm').onsubmit=saveProfile;
    if(byId('terminateAffiliate'))byId('terminateAffiliate').onclick=terminateContract;
    if(byId('affiliateWithdraw'))byId('affiliateWithdraw').onclick=requestWithdrawal;
  }
  async function loadProducts(){if(state.loading||!state.productsMore)return;state.loading=true;renderTab();try{const rows=await window.sbFetch(`products?select=id,name_ar,name_en,price,image,gallery,affiliate_commission_rate&active=eq.true&affiliate_enabled=eq.true&order=sort_order.asc&limit=${PAGE}&offset=${state.productOffset}`);state.products.push(...rows);state.productOffset+=rows.length;state.productsMore=rows.length===PAGE}catch(error){toast(String(error.message||error))}finally{state.loading=false;renderTab()}}
  async function loadCommissions(){if(state.loading||!state.commissionsMore)return;state.loading=true;try{const rows=await window.sbFetch(`affiliate_commissions?select=*&order=created_at.desc&limit=${PAGE}&offset=${state.commissionOffset}`);state.commissions.push(...rows);state.commissionOffset+=rows.length;state.commissionsMore=rows.length===PAGE}catch(error){toast(String(error.message||error))}finally{state.loading=false;renderTab()}}
  async function loadWithdrawals(){if(state.loading||!state.withdrawalsMore)return;state.loading=true;try{const rows=await window.sbFetch(`affiliate_withdrawals?select=*&order=created_at.desc&limit=${PAGE}&offset=${state.withdrawalOffset}`);state.withdrawals.push(...rows);state.withdrawalOffset+=rows.length;state.withdrawalsMore=rows.length===PAGE}catch(error){toast(String(error.message||error))}finally{state.loading=false;renderTab()}}
  async function saveProfile(event){event.preventDefault();const raw=Object.fromEntries(new FormData(event.currentTarget));raw.payout_details={details:raw.payout_details||''};try{await rpc('affiliate_update_profile',{p_payload:raw});toast(t('تم حفظ الملف','Profile saved'));await boot()}catch(error){toast(String(error.message||error))}}
  async function terminateContract(){if(!confirm(t('هل تريد إنهاء التعاقد؟ ستتوقف روابط وأدوات التسويق فورًا.','End the contract? Marketing links and tools will stop immediately.')))return;const reason=prompt(t('سبب الإنهاء (اختياري)','Reason (optional)'),'');if(reason===null)return;try{await rpc('affiliate_terminate_contract',{p_reason:reason});toast(t('تم إنهاء التعاقد','Contract ended'));await boot()}catch(error){toast(String(error.message||error))}}
  async function requestWithdrawal(){const amount=Number(prompt(t('اكتب مبلغ السحب','Enter withdrawal amount'),Number(state.dashboard.available_earnings||0).toFixed(2)));if(!amount)return;const method=prompt(t('طريقة الاستلام','Payout method'),state.dashboard.partner.payout_method||'bank_transfer');if(!method)return;try{await rpc('affiliate_request_withdrawal',{p_amount:amount,p_method:method,p_details:state.dashboard.partner.payout_details||{}});toast(t('تم إرسال طلب السحب','Withdrawal requested'));await boot()}catch(error){toast(String(error.message||error))}}
  async function showAssets(productId,link){try{const rows=await window.sbFetch(`affiliate_marketing_assets?select=*&active=eq.true&product_id=eq.${encodeURIComponent(productId)}&order=sort_order.asc&limit=${PAGE}`);const box=document.createElement('div');box.style.cssText='position:fixed;inset:0;background:#0008;z-index:99999;display:grid;place-items:center;padding:16px';box.innerHTML=`<div class="affiliate-panel" style="width:min(620px,100%);max-height:85vh;overflow:auto;padding:18px"><div class="affiliate-actions" style="justify-content:space-between"><h2>${t('مواد التسويق','Marketing assets')}</h2><button class="affiliate-btn" data-close>×</button></div><div class="affiliate-link">${esc(link)}</div>${rows.length?rows.map(a=>`<div class="affiliate-card" style="margin-top:9px"><strong>${esc(en()?(a.title_en||a.title_ar):(a.title_ar||a.title_en))}</strong><p>${esc(en()?(a.content_en||a.content_ar):(a.content_ar||a.content_en))}</p>${a.media_url?`<a class="affiliate-btn" target="_blank" rel="noopener" href="${esc(a.media_url)}">${t('فتح الملف','Open asset')}</a>`:''}</div>`).join(''):`<p class="affiliate-empty">${t('صور المنتج والرابط جاهزان للمشاركة.','The product images and link are ready to share.')}</p>`}</div>`;box.onclick=e=>{if(e.target===box||e.target.closest('[data-close]'))box.remove()};document.body.appendChild(box)}catch(error){toast(String(error.message||error))}}
  async function copy(value){await navigator.clipboard.writeText(value);toast(t('تم النسخ','Copied'))}
  async function share(value){if(navigator.share)await navigator.share({text:value});else await copy(value)}
  window.addEventListener('bariq:languagechange',()=>boot());
  boot();
})();
