// @ts-nocheck
import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createTrainingEngine } from "../_shared/training-engine.generated.mjs";
import { getSupabasePublishableKey, getSupabaseSecretKey } from "../_shared/supabase_keys.ts";

const SB = Deno.env.get("SUPABASE_URL") || "https://knleehjjejfeobcmpwnw.supabase.co";
const SECRET = getSupabaseSecretKey(), PUBLIC = getSupabasePublishableKey();
const origins=new Set(["https://bariqgifts.com","https://www.bariqgifts.com","https://admin.bariqgifts.com","http://localhost:3000","http://127.0.0.1:3000"]);
function response(req:Request,body:unknown,status=200){const o=req.headers.get("origin")||"";return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","access-control-allow-origin":origins.has(o)?o:"https://bariqgifts.com","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"POST, OPTIONS","vary":"Origin"}});}
function dbHeaders(extra={}){return {apikey:SECRET,authorization:`Bearer ${SECRET}`,"content-type":"application/json",...extra};}
function authorized(req:Request){const api=String(req.headers.get("apikey")||""),bearer=String(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");return Boolean(PUBLIC&&(api===PUBLIC||bearer===PUBLIC))||Boolean(SECRET&&(api===SECRET||bearer===SECRET));}
async function rows(path:string){const r=await fetch(`${SB}/rest/v1/${path}`,{headers:dbHeaders()});if(!r.ok)throw new Error(`database ${r.status}: ${await r.text()}`);return await r.json();}
async function all(table:string,select:string,tail=""){const out=[];for(let offset=0;;offset+=500){const page=await rows(`${table}?select=${encodeURIComponent(select)}&limit=500&offset=${offset}${tail}`);out.push(...page);if(page.length<500)break;}return out;}
const KNOWLEDGE="id,question,answer,category,keywords,input_type,param_type,param_example,action_name,action_value,active,usage_count,created_at,updated_at";
const PRODUCTS="id,name_ar,name_en,description_ar,description_en,category_id,subcategory_id,price,old_price,stock,image,gallery,categories,rating,featured,active,sort_order,timer_end,created_at";
async function catalog(){const [knowledge,products,categories,subcategories]=await Promise.all([all("bot_knowledge",KNOWLEDGE,"&active=eq.true&order=id.desc"),all("products",PRODUCTS,"&active=eq.true&order=sort_order.asc"),all("categories","*","&active=eq.true&order=sort_order.asc"),all("subcategories","*","&active=eq.true&order=sort_order.asc")]);return {knowledge,products,categories,subcategories};}
function phone(value:unknown){let x=String(value||"").replace(/\D/g,"");if(x.startsWith("00"))x=x.slice(2);if(x.startsWith("0"))x=`971${x.slice(1)}`;else if(x.startsWith("5")&&x.length===9)x=`971${x}`;return x;}
function dbAdapter(sender:string){return async(path:string,opts:any={})=>{if(path.startsWith("orders?")&&!sender)return [];const r=await fetch(`${SB}/rest/v1/${path}`,{method:opts.method||"GET",headers:dbHeaders(opts.headers||{}),body:opts.body});if(!r.ok)throw new Error(`database ${r.status}: ${await r.text()}`);const data=await r.json().catch(()=>[]);return path.startsWith("orders?")?(Array.isArray(data)?data:[]).filter(x=>phone(x.customer_phone)===phone(sender)):data;};}
function envelope(out:any){const r=out.result||{},products=Array.isArray(r.products)?r.products:[];return {...r,reply:String(r.text||""),action:r.type==="silent"?"silent":String(r.systemAction||r.type||"answer").toLowerCase(),knowledge_id:r.knowledgeId||r.match?.id||null,entities:out.state||{},context:out.state||{},products,state:out.state||{},conversation:out.conversation||[],unanswered:Boolean(r.unanswered||r.type==="silent"),debug:out.debug||{}};}

serve(async(req)=>{if(req.method==="OPTIONS")return response(req,{ok:true});if(req.method!=="POST")return response(req,{error:"method not allowed"},405);if(!authorized(req))return response(req,{error:"unauthorized"},401);try{const body=await req.json(),message=String(body.message||"").trim().slice(0,4000);if(!message&&!body.image_url)return response(req,{error:"message required"},400);const context=body.context||{},data=await catalog();const engine=createTrainingEngine({...data,conversation:Array.isArray(body.conversation)?body.conversation:[],state:context.current_state||context,memories:context.memories||[],summary:context.conversation_summary||null,settings:{useLLM:false},sbFetch:dbAdapter(String(context.sender_phone||""))});if(body.image_url){const image=await engine.image(String(body.image_url),message);return response(req,envelope({result:{type:image.products?.length?"products":"silent",text:"",products:image.products||[],systemAction:"IMAGE_PRODUCT_SEARCH",liveData:true},...engine.snapshot()}));}return response(req,envelope(await engine.message(message)));}catch(error){console.error("training engine",error);return response(req,{error:"engine unavailable"},500);}});
